FROM ubuntu:latest
USER root
COPY .ssh /root/.ssh
RUN chown root:root /root/.ssh
RUN chmod -R 600 /root/.ssh
ENV PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN apt-get update && apt-get upgrade
RUN apt-get install -y git python3 python3-dev python3-pip pdf2svg poppler-utils wget unzip
RUN apt-get clean && apt-get autoclean && rm -rf /var/lib/apt/lists/*
COPY doc_process /doc_process/doc_process
ADD docker/requirements.txt /doc_process/
RUN pip3 install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --upgrade pip
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install Cython --install-option="--no-cython-compile"
RUN cd /doc_process/ && pip install -r requirements.txt && rm -rf /root/.ssh
RUN ln -s /doc_process/doc_process/data /data
EXPOSE 8000
CMD cd /doc_process/doc_process/app && python3 server.py document_process
